services:
  web:
    image: "webspy:latest"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    container_name: "webspy"
    restart: unless-stopped
    ports:
      - "1984:1984"
    environment:
      - DB_URL=/web_spy
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - WEB_BIND_IP=0.0.0.0
      - WEB_BIND_PORT=1984
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: web_spy
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8005:3306"